In [3]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder  # for Encoding Ordinal(input) Data Columns
from sklearn.preprocessing import OneHotEncoder   # for Encoding Nominal Data Columns
from sklearn.preprocessing import LabelEncoder     # for Encoding Ordinal(output) Column

from sklearn.compose import ColumnTransformer

In [4]:
df=pd.read_csv('encoded_dataset.csv')

In [5]:
df

     Age  Income  Gender       City Education Purchased
0     56   55342    Male  Islamabad        UG        No
1     46   67157  Female     Lahore        HS       Yes
2     32   97863  Female    Karachi        UG        No
3     25   82083    Male  Islamabad        HS       Yes
4     38   95733  Female  Islamabad        HS        No
..   ...     ...     ...        ...       ...       ...
195   23   53049  Female    Karachi        UG       Yes
196   49   98385  Female  Islamabad        UG       Yes
197   21   70158  Female     Lahore        HS       Yes
198   28   95417  Female     Lahore        PG       Yes
199   34   53289    Male     Lahore        UG       Yes

[200 rows x 6 columns]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train , y_test =train_test_split(df.iloc[:,[2,3,4]] , df.iloc[: ,-1 ]  , test_size=0.1)

In [7]:
clt=ColumnTransformer([
    ('trns1', OrdinalEncoder(categories=[['HS','UG','PG']]),['Education']),
     ('trns2',OneHotEncoder(sparse_output=False , drop='first') ,['Gender','City'])
     ])

In [10]:
x_train_scaled= clt.fit_transform(x_train)

In [11]:
x_train_scaled

array([[2., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [0., 1., 0., 1.],
       [2., 1., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [2., 0., 1., 0.],
       [2., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [2., 1., 0., 1.],
       [2., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 1.],
       [0., 1., 0., 1.],
       [2., 1., 0., 1.],
       [2., 1., 0., 1.],
       [0., 0., 0., 0.],
       [2., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [2., 1., 0., 1.],
       [2., 0., 0., 1.],
       [1., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 0.],
       [2., 0., 0., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [2., 0., 0., 1.],
       [1., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [2., 0., 1., 0.],
       [1., 0., 0., 1.],
       [2., 0., 0., 0.],
       [1., 0., 1., 0.],
       [2., 1., 1., 0.],
       [0., 1., 0., 1.],
       [2., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 1.],
       [1., 1., 1., 0.],
       [2., 0., 0., 1.],
       [2., 1., 0., 0.],
       [1., 1., 0., 1.],
       [0., 0., 1., 0.],
       [2., 1., 1., 0.],
       [2., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 1., 0., 1.],
       [2., 1., 0., 1.],
       [2., 0., 1., 0.],
       [1., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 1., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [2., 1., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [2., 1., 0., 0.],
       [2., 1., 0., 1.],
       [2., 1., 1., 0.],
       [2., 0., 1., 0.],
       [2., 1., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 1., 0.],
       [2., 1., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.],
       [2., 1., 0., 0.],
       [0., 1., 0., 1.],
       [2., 0., 1., 0.],
       [2., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [2., 1., 0., 1.],
       [2., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 0., 1.],
       [2., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 1.],
       [1., 1., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [2., 1., 0., 0.],
       [2., 1., 0., 1.],
       [0., 1., 1., 0.],
       [2., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 1.],
       [1., 1., 0., 1.],
       [1., 0., 1., 0.],
       [2., 0., 0., 1.],
       [2., 0., 0., 1.],
       [2., 0., 1., 0.],
       [2., 1., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [2., 1., 0., 0.],
       [2., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [2., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 1.],
       [1., 1., 0., 1.],
       [0., 1., 1., 0.],
       [2., 1., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 1., 1., 0.],
       [1., 1., 0., 1.],
       [0., 0., 1., 0.],
       [1., 1., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.],
       [2., 1., 0., 0.],
       [0., 1., 0., 1.],
       [0., 0., 0., 1.],
       [1., 1., 0., 1.],
       [0., 1., 0., 0.],
       [2., 0., 0., 0.],
       [2., 1., 1., 0.],
       [2., 0., 0., 1.],
       [2., 0., 1., 0.],
       [2., 0., 0., 1.],
       [0., 0., 0., 1.],
       [2., 1., 0., 1.],
       [2., 0., 0., 0.],
       [2., 1., 1., 0.],
       [1., 1., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 1.],
       [2., 0., 0., 0.],
       [1., 1., 0., 1.],
       [1., 1., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 1.],
       [2., 1., 0., 0.],
       [2., 1., 0., 0.],
       [2., 1., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 1., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [2., 0., 0., 1.]])

In [12]:
x_test_scaled=clt.fit_transform(x_test)

In [13]:
x_test_scaled

array([[1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [2., 1., 1., 0.],
       [2., 0., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 0., 1.],
       [0., 1., 1., 0.],
       [2., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [2., 0., 1., 0.],
       [1., 0., 0., 1.],
       [2., 0., 0., 1.],
       [1., 0., 0., 0.],
       [2., 0., 1., 0.]])